[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "numpy",
    "versioneer[toml]>=0.28"
]
build-backend = "setuptools.build_meta"

# Project metadata
[project]
name = "csxtools"
version = "1.0.0"
description = "Python library for tools to be used at the Coherent Soft X-ray scattering (CSX) beamline at NSLS-II."
readme = "README.md"
authors = [
    { name = "Brookhaven National Laboratory" },
]
license = { text = "BSD" }
keywords = ["Xray Analysis"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: C",
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

# Optional dependencies (extras)
[project.optional-dependencies]
dev = [
    "ruff>=0.4.0",
    "codecov",
    "coveralls",
    "pytest",
    "sphinx",
    "sphinx-bootstrap-theme",
]
complete = [
    "databroker",
    "ipywidgets",
    "matplotlib",
]

# Setuptools configuration for C extensions
[tool.setuptools.packages.find]
exclude = ["src", "tests"]

[tool.setuptools.dynamic]
ext_modules = [{name = "csxtools.ext.fastccd", sources=["src/fastccdmodule.c", "src/fastccd.c"], extra_compile_args=["-fopenmp"], extra_link_args=["-lgomp"]},
    {name = "csxtools.ext.axis1", sources=["src/axis1module.c", "src/axis1.c"], extra_compile_args=["-fopenmp"], extra_link_args=["-lgomp"]},
    {name = "csxtools.ext.image", sources=["src/imagemodule.c", "src/image.c"], extra_compile_args=["-fopenmp"], extra_link_args=["-lgomp"]},
    {name = "csxtools.ext.phocount", sources=["src/phocountmodule.c", "src/phocount.c"], extra_compile_args=["-fopenmp"], extra_link_args=["-lgomp"]}]


# Ruff configuration
[tool.ruff]
exclude = [
    "examples",
    "doc",
    "build",
    "dist",
    "csxtools.egg-info",
    "__pycache__"
]