[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "numpy",
    "versioneer[toml]>=0.28"
]
build-backend = "setuptools.build_meta"
[tool.ruff]
exclude = [
    "examples",
    "doc",
    "build",
    "dist",
    "csxtools.egg-info",
    "__pycache__"
]
[project.optional-dependencies]
dev = [
    "pytest",
    "ruff>=0.4.0",
]

docs = [
    "sphinx",
    "sphinx-bootstrap-theme",
]

ci = [
    "codecov",
    "coveralls",
]
[project]
name = "csxtools"
version = "0.0.0"  # This will be overwritten by Versioneer in setup.py
description = "Python library for CSX beamline tools at NSLS-II"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Brookhaven National Laboratory" }]
requires-python = ">=3.8"
dependencies = [
    "numpy"
]
